---
 - name: Push ebgp configuration from a template, and commit.
   hosts: "{{ device }}"
   connection: local
   gather_facts: no

   tasks:

   - name: Push ebgp configuration from a template, and commit.
     junos_template:
      #http://docs.ansible.com/ansible/junos_template_module.html
      provider: "{{  credentials }}"
      src: "{{ playbook_dir }}/add_ebgp.j2"
      comment: "add ebgp neighbor from Ansible"

   - name: Send Slack notification
     local_action:
       module: slack
       #http://docs.ansible.com/ansible/slack_module.html
       username: "Playbook pb.ebgp.yml with template add_ebgp.j2"
       channel: general
       token: T4US01RHT/B4V7B1ALD/jPwocueKb3RWjK1IJ2OuNFoa
       icon_url: "https://www.ansible.com/hs-fs/hub/330046/file-448313641-png/favicon.png"
       msg: "configuration commited on device {{ inventory_hostname }}"
