---
 - name: create BGP Openconfig configuration
   hosts: Openconfig_Routers
   connection: local
   gather_facts: no
   tags:
   - configuration

   tasks:

   - name: Backup locally the config from the routers. Push on routers OC BGP config from templates, and commit.
     junos_template:
      #http://docs.ansible.com/ansible/junos_template_module.html
      provider: "{{  credentials }}"
      src: "{{ playbook_dir }}/openconfig_bgp.j2"
      comment: "OC BGP configuration from Ansible"
      backup: true

   - name: Send Slack notification to the team
     local_action:
       module: slack
       #http://docs.ansible.com/ansible/slack_module.html
       username: "Ansible on {{ inventory_hostname }}"
       channel: general
       token: T2MBN64JX/B2N0Z2MEU/1OoB46XLX6Q1oFf89Xl2X9gq
       icon_url: "https://www.ansible.com/hs-fs/hub/330046/file-448313641-png/favicon.png"
       msg: "configuration commited using pb.oc.bgp.yaml"

 - name: wait for peers to establish BGP connections
   hosts: localhost
   gather_facts: no

   tasks:
   - pause: seconds=20
     #http://docs.ansible.com/ansible/pause_module.html

 - name: check bgp states
   hosts: Openconfig_Routers
   connection: local
   gather_facts: no
   tags:
   - audit

   tasks:
   - name: check bgp peers states
     junos_command:
      #http://docs.ansible.com/ansible/junos_command_module.html
      provider: "{{  credentials }}"
      commands:
       - show bgp neighbor "{{ item.address }}"
      waitfor:
      - "result[0].bgp-information.bgp-peer.peer-state eq Established"
      retries: 10
      interval: 2
     with_items:
     - "{{ bgp_neighbors }}"

   - name: check if junos devices learnt some routes with BGP
     junos_command:
      #http://docs.ansible.com/ansible/junos_command_module.html
      provider: "{{  credentials }}"
      commands:
       - show route receive-protocol bgp "{{ item.address }}" table inet.0
      waitfor:
       - "result[0].route-information.route-table.total-route-count gt 10"
      retries: 10
      interval: 2
     with_items:
     - "{{ bgp_neighbors }}"

   - name: Send Slack notification to the team
     local_action:
       module: slack
       #http://docs.ansible.com/ansible/slack_module.html
       icon_url: "https://www.ansible.com/hs-fs/hub/330046/file-448313641-png/favicon.png"
       token: T4US01RHT/B4V7B1ALD/jPwocueKb3RWjK1IJ2OuNFoa
       username: "Ansible on {{ inventory_hostname }}"
       channel: general
       msg: "audit completed using pb.oc.bgp.yaml"
