---
 - name: remove an ebgp neighbor.
   hosts: "{{ device }}"
   connection: local
   gather_facts: no

   tasks:

   - name: remove an ebgp neighbor.
     junos_template:
      #http://docs.ansible.com/ansible/junos_template_module.html
      provider: "{{  credentials }}"
      src: "{{ playbook_dir }}/remove_ebgp.j2"
      config_format: set
      comment: "remove an ebgp neighbor. Configuration done by Ansible"

   - name: Send Slack notification
     local_action:
       module: slack
       #http://docs.ansible.com/ansible/slack_module.html
       username: "Playbook pb.remove.ebgp.yml with template remove_ebgp.j2"
       channel: general
       token: T4US01RHT/B4V7B1ALD/jPwocueKb3RWjK1IJ2OuNFoa
       icon_url: "https://www.ansible.com/hs-fs/hub/330046/file-448313641-png/favicon.png"
       msg: "configuration commited on device {{ inventory_hostname }}"
