---
 - name: Backup locally the config from the devices. Push on devices configuration from templates, and commit.
   hosts: "{{ device }}"
   connection: local
   gather_facts: no

   tasks:

   - name: Backup locally the config from the devices. Push on devices configuration from templates, and commit.
     junos_template:
      #http://docs.ansible.com/ansible/junos_template_module.html
      provider: "{{  credentials }}"
      src: "{{ playbook_dir }}/{{ template }}"
      comment: "configuration from Ansible"
      backup: true

   - name: Send Slack notification
     local_action:
       module: slack
       #http://docs.ansible.com/ansible/slack_module.html
       username: "Playbook pb.template.yml with template {{ template }}"
       channel: general
       token: T4US01RHT/B4V7B1ALD/jPwocueKb3RWjK1IJ2OuNFoa
       icon_url: "https://www.ansible.com/hs-fs/hub/330046/file-448313641-png/favicon.png"
       msg: "configuration commited on device {{ inventory_hostname }}"
